language: csharp
mono: none
addons:
    chrome: stable
stages:
    - "Build Fat Framework"
    - "Test Templates"
jobs:
    include:
        - stage: "Build Fat Framework"
          dotnet: 3.1.102
          name: "Building the Fat Framework"
          script:
              - dotnet build Yontech.Fat/
              - dotnet build Yontech.Fat.TestAdapter/
              - dotnet build Yontech.Fat.ConsoleRunner/
              - dotnet test tests/YonTech.Fat.Tests
        - stage: "Test Templates"
          dotnet: 3.1.102
          name: "Test template using dotnetcore 3.1"
          script:
              - dotnet test Yontech.Fat.Templates/templates/CreateFatProject/
              - dotnet test Yontech.Fat.Templates/templates/CreateConsoleFatProject/
              - dotnet run --project tests/RealWorldProjects/RealWorld.Angular.Tests/RealWorld.Angular.Tests.csproj
        - dotnet: 2.1.502
          name: "Test template using dotnetcore 2.1"
          script: dotnet test Yontech.Fat.Templates/templates/CreateFatProjectWithSamples/
