// <auto-generated/>
namespace Yontech.Fat
{
    //
    // Summary:
    //     Representations of keys able to be pressed that are not text keys for sending
    //     to the browser.
    public static class KeyboardKeys
    {
        //
        // Summary:
        //     Represents the NUL keystroke.
        public static readonly string Null = OpenQA.Selenium.Keys.Null;
        //
        // Summary:
        //     Represents the number pad 0 key.
        public static readonly string NumberPad0 = OpenQA.Selenium.Keys.NumberPad0;
        //
        // Summary:
        //     Represents the number pad 1 key.
        public static readonly string NumberPad1 = OpenQA.Selenium.Keys.NumberPad1;
        //
        // Summary:
        //     Represents the number pad 2 key.
        public static readonly string NumberPad2 = OpenQA.Selenium.Keys.NumberPad2;
        //
        // Summary:
        //     Represents the number pad 3 key.
        public static readonly string NumberPad3 = OpenQA.Selenium.Keys.NumberPad3;
        //
        // Summary:
        //     Represents the number pad 4 key.
        public static readonly string NumberPad4 = OpenQA.Selenium.Keys.NumberPad4;
        //
        // Summary:
        //     Represents the number pad 5 key.
        public static readonly string NumberPad5 = OpenQA.Selenium.Keys.NumberPad5;
        //
        // Summary:
        //     Represents the number pad 6 key.
        public static readonly string NumberPad6 = OpenQA.Selenium.Keys.NumberPad6;
        //
        // Summary:
        //     Represents the number pad 7 key.
        public static readonly string NumberPad7 = OpenQA.Selenium.Keys.NumberPad7;
        //
        // Summary:
        //     Represents the number pad 8 key.
        public static readonly string NumberPad8 = OpenQA.Selenium.Keys.NumberPad8;
        //
        // Summary:
        //     Represents the number pad 9 key.
        public static readonly string NumberPad9 = OpenQA.Selenium.Keys.NumberPad9;
        //
        // Summary:
        //     Represents the number pad multiplication key.
        public static readonly string Multiply = OpenQA.Selenium.Keys.Multiply;
        //
        // Summary:
        //     Represents the number pad addition key.
        public static readonly string Add = OpenQA.Selenium.Keys.Add;
        //
        // Summary:
        //     Represents the number pad thousands separator key.
        public static readonly string Separator = OpenQA.Selenium.Keys.Separator;
        //
        // Summary:
        //     Represents the equal sign key.
        public static readonly string Equal = OpenQA.Selenium.Keys.Equal;
        //
        // Summary:
        //     Represents the number pad subtraction key.
        public static readonly string Subtract = OpenQA.Selenium.Keys.Subtract;
        //
        // Summary:
        //     Represents the number pad division key.
        public static readonly string Divide = OpenQA.Selenium.Keys.Divide;
        //
        // Summary:
        //     Represents the function key F1.
        public static readonly string F1 = OpenQA.Selenium.Keys.F1;
        //
        // Summary:
        //     Represents the function key F2.
        public static readonly string F2 = OpenQA.Selenium.Keys.F2;
        //
        // Summary:
        //     Represents the function key F3.
        public static readonly string F3 = OpenQA.Selenium.Keys.F3;
        //
        // Summary:
        //     Represents the function key F4.
        public static readonly string F4 = OpenQA.Selenium.Keys.F4;
        //
        // Summary:
        //     Represents the function key F5.
        public static readonly string F5 = OpenQA.Selenium.Keys.F5;
        //
        // Summary:
        //     Represents the function key F6.
        public static readonly string F6 = OpenQA.Selenium.Keys.F6;
        //
        // Summary:
        //     Represents the function key F7.
        public static readonly string F7 = OpenQA.Selenium.Keys.F7;
        //
        // Summary:
        //     Represents the function key F8.
        public static readonly string F8 = OpenQA.Selenium.Keys.F8;
        //
        // Summary:
        //     Represents the function key F9.
        public static readonly string F9 = OpenQA.Selenium.Keys.F9;
        //
        // Summary:
        //     Represents the function key F10.
        public static readonly string F10 = OpenQA.Selenium.Keys.F10;
        //
        // Summary:
        //     Represents the function key F11.
        public static readonly string F11 = OpenQA.Selenium.Keys.F11;
        //
        // Summary:
        //     Represents the function key F12.
        public static readonly string F12 = OpenQA.Selenium.Keys.F12;
        //
        // Summary:
        //     Represents the number pad decimal separator key.
        public static readonly string Decimal = OpenQA.Selenium.Keys.Decimal;
        //
        // Summary:
        //     Represents the function key META.
        public static readonly string Meta = OpenQA.Selenium.Keys.Meta;
        //
        // Summary:
        //     Represents the semi-colon key.
        public static readonly string Semicolon = OpenQA.Selenium.Keys.Semicolon;
        //
        // Summary:
        //     Represents the Insert key.
        public static readonly string Insert = OpenQA.Selenium.Keys.Insert;
        //
        // Summary:
        //     Represents the Cancel keystroke.
        public static readonly string Cancel = OpenQA.Selenium.Keys.Cancel;
        //
        // Summary:
        //     Represents the Help keystroke.
        public static readonly string Help = OpenQA.Selenium.Keys.Help;
        //
        // Summary:
        //     Represents the Backspace key.
        public static readonly string Backspace = OpenQA.Selenium.Keys.Backspace;
        //
        // Summary:
        //     Represents the Tab key.
        public static readonly string Tab = OpenQA.Selenium.Keys.Tab;
        //
        // Summary:
        //     Represents the Clear keystroke.
        public static readonly string Clear = OpenQA.Selenium.Keys.Clear;
        //
        // Summary:
        //     Represents the Return key.
        public static readonly string Return = OpenQA.Selenium.Keys.Return;
        //
        // Summary:
        //     Represents the Enter key.
        public static readonly string Enter = OpenQA.Selenium.Keys.Enter;
        //
        // Summary:
        //     Represents the Shift key.
        public static readonly string Shift = OpenQA.Selenium.Keys.Shift;
        //
        // Summary:
        //     Represents the Shift key.
        public static readonly string LeftShift = OpenQA.Selenium.Keys.LeftShift;
        //
        // Summary:
        //     Represents the Control key.
        public static readonly string Control = OpenQA.Selenium.Keys.Control;
        //
        // Summary:
        //     Represents the Control key.
        public static readonly string LeftControl = OpenQA.Selenium.Keys.LeftControl;
        //
        // Summary:
        //     Represents the Alt key.
        public static readonly string Alt = OpenQA.Selenium.Keys.Alt;
        //
        // Summary:
        //     Represents the Alt key.
        public static readonly string LeftAlt = OpenQA.Selenium.Keys.LeftAlt;
        //
        // Summary:
        //     Represents the Delete key.
        public static readonly string Delete = OpenQA.Selenium.Keys.Delete;
        //
        // Summary:
        //     Represents the Pause key.
        public static readonly string Pause = OpenQA.Selenium.Keys.Pause;
        //
        // Summary:
        //     Represents the Spacebar key.
        public static readonly string Space = OpenQA.Selenium.Keys.Space;
        //
        // Summary:
        //     Represents the Page Up key.
        public static readonly string PageUp = OpenQA.Selenium.Keys.PageUp;
        //
        // Summary:
        //     Represents the Page Down key.
        public static readonly string PageDown = OpenQA.Selenium.Keys.PageDown;
        //
        // Summary:
        //     Represents the End key.
        public static readonly string End = OpenQA.Selenium.Keys.End;
        //
        // Summary:
        //     Represents the Home key.
        public static readonly string Home = OpenQA.Selenium.Keys.Home;
        //
        // Summary:
        //     Represents the left arrow key.
        public static readonly string Left = OpenQA.Selenium.Keys.Left;
        //
        // Summary:
        //     Represents the left arrow key.
        public static readonly string ArrowLeft = OpenQA.Selenium.Keys.ArrowLeft;
        //
        // Summary:
        //     Represents the up arrow key.
        public static readonly string Up = OpenQA.Selenium.Keys.Up;
        //
        // Summary:
        //     Represents the up arrow key.
        public static readonly string ArrowUp = OpenQA.Selenium.Keys.ArrowUp;
        //
        // Summary:
        //     Represents the right arrow key.
        public static readonly string Right = OpenQA.Selenium.Keys.Right;
        //
        // Summary:
        //     Represents the right arrow key.
        public static readonly string ArrowRight = OpenQA.Selenium.Keys.ArrowRight;
        //
        // Summary:
        //     Represents the Left arrow key.
        public static readonly string Down = OpenQA.Selenium.Keys.Down;
        //
        // Summary:
        //     Represents the Left arrow key.
        public static readonly string ArrowDown = OpenQA.Selenium.Keys.ArrowDown;
        //
        // Summary:
        //     Represents the Escape key.
        public static readonly string Escape = OpenQA.Selenium.Keys.Escape;
        //
        // Summary:
        //     Represents the function key COMMAND.
        public static readonly string Command = OpenQA.Selenium.Keys.Command;
    }
}
